Xml annotations
wmde/fundraising-donations pull request #165
Opened 2021-09-27 07:57 UTC by Abban

Ticket: https://phabricator.wikimedia.org/T286893

2021-09-27 10:49 UTC, gbirke requested changes
Looks good so far.

You can ignore the warnings on nullable IDs. They are nullable for historic reasons (2016 PHP and Doctrine not being as type safe as today) and will be improved upon in the new model (taking advice and ideas from https://matthiasnoback.nl/2018/05/when-and-where-to-determine-the-id-of-an-entity/ )

2021-09-27 10:49 UTC, gbirke commented on src/DonationContextFactory.php
> +		return new XmlDriver( self::DOCTRINE_CLASS_MAPPING_DIRECTORY );
You can remove the comment now, it doesn't apply any more.

2021-09-27 10:49 UTC, gbirke commented on src/DataAccess/DoctrineEntities/Donation.php
> +	private ?string $data = null;
It's amazing that this is defined as nullable, where in practice it'll never be null. Could you adapt `getData` to return a serialized empty array instead of `null` to appease the type checkers?

2021-09-27 11:11 UTC, Abban commented on src/DataAccess/DoctrineEntities/Donation.php
> +	private ?string $data = null;
`getData` and `setData` are deprecated in favour of some explicit methods that perform the serialisation. Now might be a good time to get rid of them?

2021-10-01 12:56 UTC, gbirke approved these changes

2021-10-04 06:03 UTC, merged