Remove nullable ID from domain Donation entity
wmde/fundraising-donations pull request #218
Opened 2023-06-13 14:14 UTC by Abban

* Add a new DonationIdRepository for generating new donation IDs when a domain entity is created.
* Make domain Donation id non-nullable
* Add donationIdRepository to UseCases
* Create DonationExistsChecker for DonationRepository
* Update tests

2023-06-14 05:42 UTC, Abban commented on src/Domain/Model/Donation.php
> +		if ( $this->comment === null ) {
I think `$comment` shouldn't be nullable and instead DonationComment should be an interface with 2 implementations, (eg `DonorDonationComment` and `EmptyDonationComment`) and we check types rather than for null.

2023-06-16 12:49 UTC, gbirke requested changes

2023-06-19 05:42 UTC, Abban commented on src/Domain/Model/Donor/PersonDonor.php
> +	public function __construct( PersonName $name, Address $address, string $emailAddress ) {
You might not be running the latest stan image locally? The DonorFieldMapper test throws an error because it's passing an `Address` and not a `PostalAddress`

2023-06-19 08:56 UTC, gbirke commented on src/Domain/Model/Donor/PersonDonor.php
> +	public function __construct( PersonName $name, Address $address, string $emailAddress ) {
Ah, now I see it. Then I'd rather change the `DonorFieldMapperTest`, to preserve the tightened type. We can do that in different ways: ignoring the error in PHPStan, adding an assertion, making `ValidDonor::newAddress`` public, etc

2023-06-19 13:35 UTC, Abban commented on tests/Integration/DataAccess/DoctrineCommentFinderTest.php
> + * TODO: Refactor this test, it is confusing as it relies on magic database ID incrementation
What it really needs is for how the test models are built to be improved. I only didn't do it in thie PR because this maintenance ended up with an extremely bald yak. I can still improve it here, but should I make a ticket for it?

2023-06-28 12:38 UTC, gbirke approved these changes

2023-06-28 12:38 UTC, gbirke commented on src/DataAccess/Migrations/Version20230613080717.php
> +			'INSERT INTO last_generated_payment_id (donation_id) VALUES ((SELECT MAX(id) + 1 FROM spenden))'
I don't know where I saw it, but I have that "headcanon"/convention where I put only structure manipulation statements in the `up` method and data manipulation statements in an `postUp` method. But I don't know where I got that idea from and why someone else thought it's a good idea, so you can leave this migration as-is

2023-07-05 15:57 UTC, moiikana commented
TODO: when merging this, create a new major release because the fundraising-application will need a db migration

2023-07-11 14:21 UTC, merged