Update Doctrine ORM
wmde/fundraising-donations pull request #232
Opened 2024-02-07 08:54 UTC by Sperling-0

- Resolve the errors

Ticket: https://phabricator.wikimedia.org/T356744

2024-02-27 14:23 UTC, moiikana commented
once this is merged, create a new release

2024-02-28 09:50 UTC, moiikana approved these changes

2024-02-28 11:06 UTC, Abban requested changes

2024-02-28 11:06 UTC, Abban commented on src/DataAccess/PaymentMigration/InsertingPaymentHandler.php
> +			$stmt->executeQuery();
You need to bind the 2 values here or they won't be inserted into the query

2024-02-28 11:06 UTC, Abban commented on src/DataAccess/PaymentMigration/PaymentIdFinder.php
> +		$paymentId = $this->getPaymentIdStatement->executeQuery()->fetchOne();
The donation ID needs to be insterted into the query here.

2024-02-28 11:33 UTC, moiikana commented on src/DataAccess/PaymentMigration/InsertingPaymentHandler.php
> +			$stmt->executeQuery();
the $donationId variable also wasn't used anywhere after that change.. I would have hoped that some code checker tooling would have prevented that :(

2024-02-28 11:46 UTC, Sperling-0 commented on src/DataAccess/PaymentMigration/InsertingPaymentHandler.php
> +			$stmt->executeQuery();
Is my fix for this correct?

2024-02-28 14:16 UTC, Abban commented on src/DataAccess/PaymentMigration/InsertingPaymentHandler.php
> +			$stmt->executeQuery();
I think it needs to be:

```php
$statement->bindValue( 1, $paymentId );
$statement->bindValue( 2, $membershipId );
```

2024-02-28 14:18 UTC, Abban commented on src/DataAccess/PaymentMigration/PaymentIdFinder.php
> +		$paymentId = $this->getPaymentIdStatement->executeQuery()->fetchOne();
This should be:

```php
$this->getPaymentIdStatement->bindValue( 1, $donationId );
```

2024-02-28 14:42 UTC, Abban approved these changes

2024-02-28 14:57 UTC, merged